### ISSUE TITLE
tls_wolfssl / tlsa parameters hover

### ISSUE THREAD

**Issue by igorolhovskiy** [braams/vscode-kamailio-hover#1]
These modules are sharing parameters with generic tls module. 
Would be great to have em as well in hover.

**Comment by braams** [comment]
There are no parameter descriptions in the documentation for these modules, so they were not added automatically.
Thanks for the idea. I will add them soon.

**Comment by braams** [comment]
Parameters for these modules have been added. The updated version is available in the marketplace.
